version: '3.1'

services:
    yap:
      build: .
      restart: always
      ports:
        - 3100:80
      volumes:
        - .:/var/www/html/
    db:
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: yap_root_password
        MYSQL_DATABASE: yap
        MYSQL_USER: yap_user
        MYSQL_PASSWORD: yap_password
